name: 'Cloudflare tunnel'
description: 'run cloudflare tunnel with token'
inputs:
  CF_TOKEN:  # id of input
    description: 'Cloudflared tunnel token'
    required: true
  TIMEOUT:
    description: workflow timeout
    required: false
    default: 30
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    CF_TOKEN: ${{ inputs.CF_TOKEN}}
    TIMEOUT: ${{ inputs.TIMEOUT }}
