name: 'Cloudflare tunnel'
description: 'run cloudflare tunnel with token'
inputs:
  TUNNEL_TOKEN:  # id of input
    description: 'Cloudflared tunnel token'
    required: true
  TUNNEL_URL:
    description: local webservice url
    required: false
    default: http://localhost:8000
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    TUNNEL_TOKEN: ${{ inputs.TUNNEL_TOKEN}}
    TUNNEL_URL: ${{ inputs.TUNNEL_URL }}
